namespace :podemos do
  desc "[podemos] Add extra geographical information"
  task :geoextra_extract => :environment do

	geoextra_filename = "config/initializers/geoextra.rb"
	File.delete(geoextra_filename) if File.exist?(geoextra_filename)
	geoextra_file = File.open(geoextra_filename, 'a')
	geoextra_file.puts "# File generated by geoextra_extract task, please don't modify\nmodule Podemos\n\tclass GeoExtra\n"
	geoextra_file.puts "\t\tISLANDS = {"

    CSV.read("db/podemos/islas.tsv", { :col_sep => "\t"}).each do |island|
    	geoextra_file.puts "\t\t\t'#{island[0]}' => [ '#{island[2]}', '#{island[3]}'],"
    end

	geoextra_file.puts "\t\t}"
	geoextra_file.puts "\t\tAUTONOMIES = {"

	CSV.read("db/podemos/comunidades.tsv", { :col_sep => "\t"}).each do |autonomy|
    	geoextra_file.puts "\t\t\t'#{autonomy[0]}' => [ '#{autonomy[2]}', '#{autonomy[3]}'],"
	end
	geoextra_file.puts "\t\t}\n\tend\nend"

	geoextra_file.close
  end
end




