namespace :podemos do
  desc "[podemos] Add extra geographical information"
  task :geoextra_extract => :environment do

	geoextra_filename = "config/initializers/geoextra.rb"
	File.delete(geoextra_filename) if File.exist?(geoextra_filename)
	geoextra_file = File.open(geoextra_filename, 'a')
	geoextra_file.puts "# File generated by geoextra_extract task, please don't modify\n"
	geoextra_file.puts "islands = {"

    CSV.read("db/podemos/islas.tsv", { :col_sep => "\t"}).each do |island|
    	geoextra_file.puts "	:#{island[0]} => [ '#{island[2]}', '#{island[3]}']"
    end

	geoextra_file.puts "}"
	geoextra_file.puts "autonomies = {"

	CSV.read("db/podemos/comunidades.tsv", { :col_sep => "\t"}).each do |autonomy|
    	geoextra_file.puts "	:#{autonomy[0]} => [ '#{autonomy[2]}', '#{autonomy[3]}']"
	end
	geoextra_file.puts "}"

	geoextra_file.close
  end
end




