source 'https://rubygems.org'

ruby '2.4.4'

gem 'active_skin'
gem 'activeadmin', '1.3.0'
gem 'airbrake'
gem 'auto_html', '1.6.4'
gem 'aws-ses', '~> 0.6.0', :require => 'aws/ses'
gem 'bootstrap-sass'
gem 'cancancan', '~> 1.9'
gem 'carmen-rails'
gem 'cocoon'
gem 'coffee-rails', '~> 4.1.0'
gem 'd3-rails'
gem 'date_validator'
gem 'devise', '~> 4.7.1'
gem 'digest-crc'
gem 'esendex'
gem 'espeak-ruby', require: 'espeak'
gem 'ffi-icu'
gem 'flag_shih_tzu'
gem 'font-awesome-rails', '~> 4.7'
gem 'formtastic'
gem 'formtastic-bootstrap'
gem 'friendly_id', '~> 5.1.0'
gem 'iban-tools'
gem 'jbuilder', '~> 2.0'
gem 'jquery-fileupload-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'mailcatcher' # for staging too
gem 'minitest-rails'
gem 'mini_racer'
gem 'norma43', github: 'podemos-info/norma43'
gem 'paper_trail', '~> 4.2.0'
gem 'paperclip', '~> 5.2.1'
gem 'paranoia', "~> 2.2"
gem 'pg'
gem 'phonelib'
gem 'pushmeup'
gem 'rack-openid'
gem 'rails', '5.0.7.2'
gem 'rails_autolink'
gem 'rake-progressbar'
gem 'rb-readline'
gem 'resque'
gem 'resque_mailer' # for automated email sending in background
gem 'ruby-openid'
gem 'rubypress'
gem 'sassc-rails', '>= 2.1.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'secure_headers'
gem 'simple_captcha2', require: 'simple_captcha'
gem 'spanish_vat_validators', '0.0.6'#, github: 'leio10/spanish_vat_validators'
gem 'sqlite3'
gem 'state_machines'
gem 'state_machines-activerecord'
gem 'state_machines-audit_trail'
gem 'turbolinks'
gem 'uglifier', '>= 2.7.2'
gem 'unicode'
gem 'unicorn'
gem 'validate_url'
gem 'wicked_pdf'
gem 'xmlrpc'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug', '<7.0.0'
  gem 'capistrano', '~> 3.10.2'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'launchy'
  gem 'minitest-rails-capybara'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'rails-perftest'
  gem 'rspec-rails'
  gem 'ruby-prof'
  gem 'simplecov'
  gem 'spring'
  gem 'webmock'
end

