source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '~> 4.2.2'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development

gem 'unicorn'
gem 'pg'
gem 'rb-readline'
gem 'airbrake'

gem 'devise'
gem 'cancancan', '~> 1.9'
gem 'bootstrap-sass'
gem 'formtastic'
gem 'formtastic-bootstrap'
gem 'spanish_vat_validators'
gem 'simple_captcha2', require: 'simple_captcha'
gem 'carmen-rails'
gem 'esendex'
gem 'activeadmin', github: 'activeadmin'
gem 'active_skin'
gem 'mailcatcher' # for staging too
gem 'resque', github: 'resque/resque', branch: '1-x-stable', require: 'resque/server'
gem 'aws-ses', '~> 0.6.0', :require => 'aws/ses'
gem 'kaminari'
gem 'pushmeup'
gem 'date_validator'
gem 'phone'
gem 'iban-tools'
gem 'paper_trail'
gem 'newrelic_rpm'
gem 'ffi-icu'
gem 'unicode'
gem 'rack-openid'
gem 'ruby-openid'
gem 'secure_headers'
gem 'minitest-rails'
gem 'rake-progressbar'
gem 'rails_autolink'
gem 'flag_shih_tzu'
gem 'wicked_pdf'
gem "font-awesome-rails"
gem 'friendly_id', '~> 5.1.0' 
gem 'auto_html'
gem "paranoia", :github => "radar/paranoia", :branch => "rails4"
gem 'cocoon'
gem 'paperclip'
gem 'validate_url'
gem 'rubycas-client', :git => 'git://github.com/rubycas/rubycas-client.git'

group :development, :test do
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-passenger'
  gem 'factory_girl_rails'
  gem 'byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails-perftest'
  gem 'ruby-prof'
  gem 'simplecov'
  gem 'webmock'
  gem 'minitest-reporters'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'minitest-rails-capybara'
end

